### PR TITLE
FC-825 Fix/missing db chan take

### PR DESCRIPTION
**Pull request by zonotope**
Resets were working in a repl, but not from the http api due to a missing take from the db channel.

### CODE REVIEW

**Comment by ldw1007** [comment]
@zonotope is this for FC-825?

**Comment by aaj3f** [comment]
> @zonotope is this for [FC-825](https://fluree.atlassian.net/browse/FC-825)?

@ldw1007 I didn't realize we had a ticket for that; this was @zonotope helping me get an intermediate solution for TrustClarity, but yes, it does solve that ticket adding a /reindex-fulltext HTTP endpoint

**Comment by zonotope** [comment]
> @zonotope is this for [FC-825](https://fluree.atlassian.net/browse/FC-825)?

Yes, I just updated the title. Sorry for forgetting again.

**Review by cap10morgan — APPROVED** [review]
🚂

**Pull request merged**
