### PR TITLE
FC-1169 fix issue where db-sync request failed for new server

### PR DESCRIPTION
**Pull request by ldw1007**
Fixed issue where a 'new' server could not synchronize files with an existing network.

### CODE REVIEW

**Review by cap10morgan — COMMENTED** [review]
Ah, yep. Good find!

I _think_ it should maybe be `:storage-group-read` instead of `ledger`, but I'm not 100% positive. Did you try that one too?

**Comment by ldw1007** [comment]
I verified that `:storage-group-read` works as well.

Should we use an 'or' condition preferring `group` over `ledger`?

**Comment by cap10morgan** [comment]
> I verified that `:storage-group-read` works as well.
> 
> Should we use an 'or' condition preferring `group` over `ledger`?

No they'll generally both be set, but they point to different locations within the storage subsystem. Strange that either one would work... That makes me think there might still be an issue in here.

I'll see if I can figure out what it should be.

**Review by cap10morgan — APPROVED** [review]
OK I think it should be `storage-ledger-read` as you have it. I'm not totally clear on why `:storage-read` ops are handled at this layer (as well as in the state-machine), but that's orthogonal to this PR 🤷🏻‍♂️.

**Pull request merged**
