### PR TITLE
preserve id under the old-id for nodes updated during indexing

### PR DESCRIPTION
**Pull request by zonotope**
This fixes a bug where new ledgers can't be created (and old ledgers can't be indexed) I introduced by trying to DRY up tree walking code without accounting for downstream code that relies on the previous id from index nodes to be preserved under the `old-id` key. The indexing process itself succeeds, but no garbage could be serialized because the garbage keys were not preserved. 

This patch adds back the old-id key for updated nodes, allowing them to be serialized.

### CODE REVIEW

**Review by dpetran — APPROVED** [review]

**Comment by dpetran** [comment]
This looks good to me, is there a test we could have that would have caught this? We don't necessarily have to add it here, but I'd like to slowly build up our regression test suite.

**Comment by zonotope** [comment]
> This looks good to me, is there a test we could have that would have caught this? We don't necessarily have to add it here, but I'd like to slowly build up our regression test suite.

I was thinking about how best to add a test. The difficulty is that I think it requires a full end-to-end integration test that actually serializes the index (and garbage files) to disk. I'll see if I can do that today, but I'll also merge this now without it just so the broken main doesn't block anyone.

**Comment by cap10morgan** [comment]
> > This looks good to me, is there a test we could have that would have caught this? We don't necessarily have to add it here, but I'd like to slowly build up our regression test suite.
> 
> 
> 
> I was thinking about how best to add a test. The difficulty is that I think it requires a full end-to-end integration test that actually serializes the index (and garbage files) to disk. I'll see if I can do that today, but I'll also merge this now without it just so the broken main doesn't block anyone. 
> 
> 

FYI I have a working integration test locally that I'll PR today. I wrote it on the plane on Friday.

It just tries to create, transact against, and query a ledger but using file storage instead of memory storage like the rest of the test suite.

It fails with this issue and I'll try it again with this fix merged to make sure it now passes.

**Comment by cap10morgan** [comment]
The aforementioned test: https://github.com/fluree/ledger/pull/140

**Pull request merged**
